name: Update date

on:
  push:
    branches: [ main ]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Update date
        run: |
          echo "Last updated: $(date +%Y-%m-%d)" > README.md
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add README.md
          git commit -m "Update README.md with last updated date"
          git push
